

name: Integration Pipeline


on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.0
          args: --timeout 3m

  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Testing...
        run: go test ./...
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jadhamwi249/factorial:latest